### ISSUE TITLE
Ability to populate all repos from account

### ISSUE THREAD

**Issue by mrflip** [Me1000/Githubissues#4]
Would be way fast to get started if the repos were populated automatically from my account. Any of the following would make sense, I don't know if any is more straightforward:
- All repos I have commit rights to (probably best)
- All repos in organizations I belong to
- All repos I'm watching

Given a choice between fixing Me1000/Githubissues#3 and this, I'd pick this. I wish I knew enough cappuccino to help.

flip

**Comment by Me1000** [comment]
These should be filed on http://githubissues.heroku.com/#cappuccino/issues
